name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: PHP Lint
      uses: michaelw90/PHP-Lint@1.0.0

    - name: PHPCodeSniffer
      uses: rtCamp/action-phpcs-inspection@v1.0.0
